# -*- coding: utf-8 -*-
"""ml model fyp ka latest .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzaSPEopvU5uP-65NhcMHMzCWGFE_Edu
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.naive_bayes import GaussianNB  # Won't be used (Not for regression)

import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("ppg.csv")
df.head()

df = pd.read_csv("ppg.csv")

# Drop rows where target (last column) is NaN
df = df.dropna(subset=[df.columns[-1]])

# Fill other NaN values (features) with mean
df = df.fillna(df.mean(numeric_only=True))

df.head()



TARGET = df.columns[-1]

X = df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

def evaluate_regressor(model, name, results):
    model.fit(X_train, y_train)
    preds = model.predict(X_test)

    mse = mean_squared_error(y_test, preds)
    mae = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mse)

    results[name] = {
        "MSE": mse,
        "MAE": mae,
        "RMSE": rmse
    }

    print(f"\n{name}")
    print("----------------------------")
    print("MSE :", mse)
    print("MAE :", mae)
    print("RMSE:", rmse)

    return mse

models = {
    "Linear Regression": LinearRegression(),
    "KNN Regressor": KNeighborsRegressor(),

    "Decision Tree Regressor": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "Gradient Boosting Regressor": GradientBoostingRegressor()
}

results = {}

for name, model in models.items():
    evaluate_regressor(model, name, results)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

ann = Sequential()
ann.add(Dense(64, activation='relu', input_dim=X_train.shape[1]))
ann.add(Dense(32, activation='relu'))
ann.add(Dense(1, activation='linear'))

ann.compile(optimizer='adam', loss='mse')

ann.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

ann_preds = ann.predict(X_test).flatten()

ann_mse  = mean_squared_error(y_test, ann_preds)
ann_mae  = mean_absolute_error(y_test, ann_preds)
ann_rmse = np.sqrt(ann_mse)

results["ANN"] = {
    "MSE": ann_mse,
    "MAE": ann_mae,
    "RMSE": ann_rmse
}

print("\nANN Regressor")
print("----------------------------")
print("MSE :", ann_mse)
print("MAE :", ann_mae)
print("RMSE:", ann_rmse)

results_df = pd.DataFrame(results).T
results_df = results_df.sort_values(by="MSE")
results_df

plt.figure(figsize=(10,5))   # wider figure
sns.barplot(x=results_df.index, y=results_df["MSE"], palette="viridis")
plt.xticks(rotation=40, ha='right')
plt.title("Model MSE Comparison")
plt.ylabel("MSE")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,5))
sns.barplot(x=results_df.index, y=results_df["RMSE"], palette="magma")
plt.xticks(rotation=40, ha='right')
plt.title("Model RMSE Comparison")
plt.ylabel("RMSE")
plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestRegressor

best_model = RandomForestRegressor(random_state=42)
best_model.fit(X_train, y_train)

y_pred = best_model.predict(X_test)

plt.figure(figsize=(5,5))
plt.scatter(y_test, y_pred, alpha=0.6)
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    linestyle='--'
)
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.title("Actual vs Predicted Values (Random Forest)")
plt.tight_layout()
plt.show()

residuals = y_test - y_pred

plt.figure(figsize=(5,4))
plt.scatter(y_pred, residuals, alpha=0.6)
plt.axhline(0, linestyle='--')
plt.xlabel("Predicted Values")
plt.ylabel("Residual Error")
plt.title("Residual Plot (Random Forest)")
plt.tight_layout()
plt.show()

import joblib

# Assuming your trained model variable is named 'model'
joblib.dump(best_model, 'glucose_model.pkl')

# This will download the file to your actual computer
from google.colab import files
files.download('glucose_model.pkl')